### ISSUE TITLE
Not compatible with Mix 1.3.0

### ISSUE THREAD

**Issue by VitoVan** [processone/iconv#1]
I don't know if it is appropriate to submit this issue here, but I don't know if there is any other place to go.

I use Elixir, with `{:iconv, "~> 1.0.0"}` in my `deps` section.

In the root dir of my project, I run `mix deps.get`, it works ok, after that, I run `mix`, it gives following error:

``` Elixir
=INFO REPORT==== 21-Jun-2016::14:00:20 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application iconv: :iconv_app.start(:normal, []) returned an error: {:load_failed, 'Failed to load NIF library: \'/home/foo/bar/_build/dev/lib/iconv/priv/lib/iconv.so: cannot open shared object file: No such file or directory\''}
```

I use the lastest `mix`:

``` bash
foo@bar:~/foo/bar$ mix -v
Erlang/OTP 18 [erts-7.2] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Mix 1.3.0-rc.1 (9eb4781)
```

It works fine yesterday, and this morning I just updated the version of Elixir to 1.3.0-rc. So I downgrade the mix to 1.2.6, and

``` bash
foo@bar:~/foo/bar$ rm -rf _build
foo@bar:~/foo/bar$ mix
```

Everything works fine.

I wonder, how can we make this work with mix 1.3.0? I need some feature in Elixir 1.3, it would be very convenient if so.

For now, I use mix 1.2.6 to compile the package, then switch back to mix 1.3.0 (without deleteing `_build` dir), it works fine, but this is kind of hacky.

**Comment by merqlove** [comment]
Same here

**Comment by merqlove** [comment]
Workaround with Mix 1.3.0:

``` elixir
[{:iconv, "~> 1.0.0", manager: :rebar}]
```

**Comment by VitoVan** [comment]
@merqlove Thank you, it works.

**Comment by mremond** [comment]
I checked version 1.0.10 with mix 1.7.4 and all seems to work fine.

I documented usage with Elixir and mix in README.md file, so we should be good.
