### ISSUE TITLE
Argument description?

### ISSUE THREAD

**Issue by cjbottaro** [processone/iconv#11]
Can you put in the readme what the expected arguments are? The spec just says it takes 3 iolists. Can you put some example calls in the readme?

**Comment by mremond** [comment]
This is improvement in https://github.com/processone/iconv/commit/c43da072ee857608aa12ccd0f233c28e1efbb398

The lib is used for example on ejabberd `mod_irc`: https://github.com/processone/ejabberd-contrib/blob/5c94639bf27d66bbc4ebcd2ec8f42729ec418087/mod_irc/src/mod_irc_connection.erl#L717
