### ISSUE TITLE
Does not work with mix releases in elixir 1.9

### ISSUE THREAD

**Issue by bisade** [processone/iconv#14]
Does not work with mix releases in elixir 1.9. 
See stacktrace below.

`17:13:31.775 [info]  Application iconv exited: exited in: :iconv_app.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function :p1_nif_utils.get_so_path/3 is undefined (module :p1_nif_utils is not available)
            :p1_nif_utils.get_so_path(:iconv, [:iconv], 'iconv')
            (iconv) /home/deploy/spu_etl/deps/iconv/src/iconv.erl:40: :iconv.load_nif/0
            (iconv) /home/deploy/spu_etl/deps/iconv/src/iconv_app.erl:52: :iconv_app.start/2
            (kernel) application_master.erl:277: :application_master.start_it_old/4
{"Kernel pid terminated",application_controller,"{application_start_failure,iconv,{bad_return,{{iconv_app,start,[normal,[]]},{'EXIT',{undef,[{p1_nif_utils,get_so_path,[iconv,[iconv],\"iconv\"],[]},{iconv,load_nif,0,[{file,\"/home/deploy/spu_etl/deps/iconv/src/iconv.erl\"},{line,40}]},{iconv_app,start,2,[{file,\"/home/deploy/spu_etl/deps/iconv/src/iconv_app.erl\"},{line,52}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,277}]}]}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,iconv,{bad_return,{{iconv_app,start,[normal,[]]},{'EXIT',{undef,[{p1_nif_utils,get_so_path,[iconv,[iconv],"iconv"],[]},{iconv

Crash dump is being written to: erl_crash.dump...done`

**Comment by andrhevictor** [comment]
I have the same problem. 

@bisade did you figured out how to solve this?

**Comment by prefiks** [comment]
Hello,

This file is available in p1_utils package, could you check if your app have it in deps?
Maybe you will need to add deps for p1_utils directly?

**Comment by andrhevictor** [comment]
@prefiks, yes is in the deps folder.

![image](https://user-images.githubusercontent.com/26423766/73177498-f3353a00-40ed-11ea-81f1-0b1a789cfe6d.png)

The awkward is that the app work with `iex -S mix`, but when i create a release (`mix release` or `mix distillery.release`) i get the error.

**Comment by prefiks** [comment]
Hm,

You probably can workaround this problem if you add :p1_utils to included_applications in application inside mix.exs.

I guess we would need to change .app file in iconv to denote having that app as dep.

**Comment by andrhevictor** [comment]
@prefiks Thank you. 

It worked.

**Comment by mremond** [comment]
@prefiks For long term improvement, do we need to change anything on our end?

**Comment by prefiks** [comment]
Yes, i think we can improve this, i will prepare that change

**Comment by badlop** [comment]
In the meantime, the function used from p1_utils have been copied here. This may be an acceptable definitive solution, or can be reverted and improved someday.
