### ISSUE TITLE
Stuck in upgrading dependencies because of hard coded dependency to p1_utils 1.0.13

### ISSUE THREAD

**Issue by haslinger** [processone/iconv#15]
Current version of p1_utils is 1.0.18.
An update would be nice :-)

**Comment by badlop** [comment]
Hi, did you check it works correctly with p1_utils 1.0.18 ?

**Comment by haslinger** [comment]
No, I didn't. I don't know how to test that in a general manner.

**Comment by haslinger** [comment]
Updating to 1.0.12 with the new dependency p1_utils 1.0.21 resolves the issue.
