### ISSUE TITLE
Can't compile on OTP23

### ISSUE THREAD

**Issue by joshuataylor** [processone/iconv#16]
```
===> Compiling iconv
===> Linking /home/josh/dev/sendle_ex/deps/iconv/priv/lib/iconv.so
** (Mix) Could not compile dependency :iconv, "/home/josh/.asdf/installs/elixir/1.10.3-otp-23/.mix/rebar3 bare compile --paths="/home/josh/dev/sendle_ex/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile iconv", update it with "mix deps.update iconv" or clean it with "mix deps.clean iconv"
```

Sorry for the lack of information! Is there anyway I can provide more information/stacktrace about this?

**Comment by prefiks** [comment]
Hello,

You should be able to compile this on R23, at least i have no problem with this when using rebar3 (as mix internally uses). Possibly adding --verbosity=verbose flag to mix will produce more output (but not sure if it does anything for rebar3 invocation).

There was update required for rebar3 pc plugin (it's used to compile c code) for compatibility with R23, possibly your build uses older version?

**Comment by cdybedahl** [comment]
I also had this problem. Compiling iconv failed, with this less than helpful crash dump from rebar3:

```
Error: {badmatch,[]}
[]
```

After reading here that it should work, I investigated more, and found that deleting the `_build` and `deps` directories, then fetching and compiling all dependencies, fixed the problem. So clearly something needed to be updated, although I'm still not sure what or how it could have been handled in a less rustic fashion than `rm -rf`.

**Comment by haslinger** [comment]
I have now updated rebar (and rebar 3) to it's latest version, running on OTP 23, Ubuntu 18.04, compiling iconv fails for me with:

```
==> iconv (compile)
Compiled src/iconv_app.erl
Compiled src/iconv_sup.erl
Compiled src/iconv.erl
Compiling c_src/iconv.c
/usr/bin/ld: -lerl_interface kann nicht gefunden werden
/usr/bin/ld: -lerl_interface kann nicht gefunden werden
collect2: error: ld returned 1 exit status
ERROR: sh(cc c_src/iconv.o   -L"/usr/lib/erlang/lib/erl_interface-4.0/lib" -lerl_interface -lei   -shared  -L"/usr/lib/erlang/lib/erl_interface-4.0/lib" -lerl_interface -lei -o priv/lib/iconv.so)
failed with return code 1 and the following output:
/usr/bin/ld: -lerl_interface kann nicht gefunden werden
/usr/bin/ld: -lerl_interface kann nicht gefunden werden
collect2: error: ld returned 1 exit status
```

`kann nicht gefunden werden` is German for connot be found.

Edit: Updating to {:iconv, "~> 1.0.10", git: "https://github.com/processone/iconv"} fixes the issue for me.

**Comment by badlop** [comment]
> ERROR: ... -lerl_interface

This got fixed in 81732a9fc777c23aa98a983f2b8bc8dcd1b48eff

**Comment by haslinger** [comment]
Any chance, we see a new release including the fix?

**Comment by badlop** [comment]
> Any chance, we see a new release including the fix?

Do you mean a new iconv release? If so, i've just tagged iconv 1.0.11
