### ISSUE TITLE
1.0.11 release is missing in hex.pm

### ISSUE THREAD

**Issue by dolfinus** [processone/iconv#18]
Hello.

I've tried to install 1.0.11 release to Elixir project:
```elixir
  defp deps do
    [
      ...
      {:iconv, "~> 1.0.11"}
    ]
```

but got an error:
```
** (Mix) No matching version for iconv ~> 1.0.11 (from: mix.exs) in registry

The latest version is: 1.0.10
```

It looks like there is only 1.0.10 release on hex.pm: https://hex.pm/packages/iconv
![image](https://user-images.githubusercontent.com/4661021/100540537-e7a32a00-324e-11eb-80f1-9c2080db3462.png)

Can you please upload latest release here?

**Comment by mremond** [comment]
Done, it is released.

**Comment by dolfinus** [comment]
Great, thanks!
