### ISSUE TITLE
Issue with missing data

### ISSUE THREAD

**Issue by nsweeting** [processone/iconv#21]
We're experiencing an issue with missing data when processing a stream and using `:iconv.convert/3` as part of that stream on each chunk.

As an example - using `iconv` directly against the same file (utf-16le to utf-8) - we will end up with 24 million of 24 million lines in a CSV file. When processing the file as a stream using `:iconv` - we'll end up with only 14 million lines.

Just wondering if there is any input out there on a possible reason and what we might be able to do to avoid this.

Thanks

**Comment by prefiks** [comment]
Do you call iconv.convert once on a whole file data, or do you call them on smaller chunks? This function doesn't really works on arbitrary chunks, if you use chunk that starts or end with something that isn't valid codepoint in input format, those fragments will be ignored (or maybe replaced with some character that's should signify that there is invalid character - depending on what your system iconv function does).

Also if you only need to use utf16 and utf8, you may also look at unicode module that is in standard lib of erlang (you could use this: https://www.erlang.org/doc/apps/stdlib/unicode.html#characters_to_binary/3), iconv makes sense only if you need to convert between more esoteric encodings.

**Comment by nsweeting** [comment]
Yeah - we were just calling it on smaller chunks. 

We did end up switching over to using the `:unicode` module. There does seem to be an associated performance impact though. I'm not versed in how `libiconv` functions - but I'm wondering if there is the ability to handle things like how the `:unicode` module does. Where the response can be something like `{:incomplete, encoded, rest}` - permitting the caller to carry `rest` over to the next chunk.

**Comment by prefiks** [comment]
I don't think we could do that in reliable way, libc iconv function that we use can just convert those to for example '?' character, and how that is handled depend on OS and probably locale.

**Comment by nsweeting** [comment]
Got it. Appreciate the input. Closing the issue for now. Thanks!
