### ISSUE TITLE
NIF not loaded

### ISSUE THREAD

**Issue by shdblowers** [processone/iconv#4]
Hi, I get the following error whilst trying to use inconv in my project:

```
** (ErlangError) erlang error: :nif_not_loaded
    :erlang.nif_error(:nif_not_loaded)
    /home/developer/work/project/deps/iconv/src/iconv.erl:54: :iconv.convert/3
```

I am requiring it in my `mix.exs` as:

```
{:iconv, "~> 1.0"}

```

And using it like so:

```
converted = :iconv.convert("iso-8859-1", "utf-8", text)
```

**Comment by squareduck** [comment]
In Elixir you need to add :iconv to your list of applications in mix.exs
or manually do something like

```
:application.start(:iconv)
```

Before using iconv

**Comment by shdblowers** [comment]
Thanks
