### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by wizardjedi** [processone/iconv#6]
Hi, folks.

It seems that there is the same issue in C-code. Like this: https://github.com/emqplus/erlang-iconv/issues/2

**Comment by MonsieurV** [comment]
Hey,

I've encountered the same problem (at least the segfault, I need to debug to know more).

I will try @wizardjedi  emqplus/erlang-iconv#2 fix to see how it does.

**Comment by MonsieurV** [comment]
Just as a follow up, I've tried [Zotonic/eiconv](https://github.com/zotonic/eiconv) as a replacement, and it works well for me. (no segfault for the same test cases)

**Comment by alexeyshch** [comment]
Thanks, it shouldn't crash now.

**Comment by MonsieurV** [comment]
Yes, it does fix the `segfault` issue.

Thanks @alexeyshch!
